#ifndef FLEXEARTHUI_GLOBAL_H
#define FLEXEARTHUI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FLEXEARTHUI_LIB
# define FEEARTHUI_EXPORT Q_DECL_EXPORT
#else
# define FEEARTHUI_EXPORT Q_DECL_IMPORT
#endif

#endif // FLEXEARTHUI_GLOBAL_H
